### ISSUE TITLE
Add caching for UniswapV3 PoolFetcher

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/cow-native-liquidity#17]
UniswapV3 models the concentrated liquidity, meaning each pool has some metadata and a list of Ticks representing ranged based liquidity.

Currently, there are 6060 pools and ~130k ticks indexed on UniswapV3 subgraph.
It takes ~20s to get the 6060 pools (containing only metadata for each pool)
It takes ~120s to get 130k ticks.

Initial idea was to get 6060 pools as a part of the initialization of the `UniswapV3PoolFetcher ` and then, when `fetch` function is called, get ticks from graph but only for those pools that contain the token pairs for which the `fetch` function was called. What worries me, is that number of token pairs can be high and getting ticks could take time.

Then, caching came into play. We can fetch all 130k in a background task, but it feels to me that there is no point doing this since the data will always be 8-10 blocks old, therefore useless. The only way to circumvent this is to have 
1. Initial request for 6060 pools on dapp startup
2. Send "6060" parallel request to graph to fetch ticks for each pool on each caching update (not even sure if this is feasible)

What comes to my mind is to reduce the number of tracked pools by:

1. Having a predefined list of pools (token pairs) to track, via configuration
2. Track all pairs that are fetched and frequency of them -> update only the most frequently fetched pools.

I'm in favor of doing the (2), although (1) would be probably more straightforward, since most of our trades are ETH/StableCoin and by tracking ~10 pools we would probably make the most of the UniswapV3 liquidity. 

Linking the PR for easier understaing: https://github.com/cowprotocol/cow-native-liquidity/pull/16

**Comment by MartinquaXD** [comment]
Both suggestions seems reasonable to me. Here are just a few thoughts on them:
We are commonly only considering liquidity which trades one of our base tokens with a user traded token like [here](https://github.com/cowprotocol/services/blob/main/crates/shared/src/baseline_solver.rs#L146-L165) (+ the exact pairs of user traded tokens).
I used the same approach as (2) for the native token price caching and it yielded [good results](https://github.com/gnosis/gp-v2-services/pull/1671) as long as you can keep most of the "hot" set up to date between liquidity requests.

That being said, could option (2) be further optimized by monitoring the block chain for events emitted by pools we are interested in and only fetch their updates from thegraph instead of updating all our "hot" pools every time?
That way we could either keep the "hot" set the same size and require fewer requests to thegraph, or keep increasing the size of the "hot" set as long as the number of requests stays reasonable.
Pools which have changed their state but have not been synced yet could be temporarily disabled to avoid simulation failures caused by old data.
